insert into board_tb(title, content, username, created_at) values('첫 번째 글', '블로그에 오신 것을 환영합니다.', '김민수', now());
insert into board_tb(title, content, username, created_at) values('두 번째 글', '스프링 부트로 블로그를 만듭니다.', '김민수', now());
insert into board_tb(title, content, username, created_at) values('세 번째 글', 'H2 콘솔에서 데이터를 확인해 보세요.', '박지훈', now());
insert into board_tb(title, content, username, created_at) values('네 번째 글', '머스태치로 화면을 그립니다.', '이서연', now());
insert into board_tb(title, content, username, created_at) values('5 번째 글', '볼트태클', '피카츄', now());
insert into board_tb(title, content, username, created_at) values('6 번째 글', '10만볼트', '라이츄', now());
insert into board_tb(title, content, username, created_at) values('7 번째 글', '불꽃세례', '파이리', now());
insert into board_tb(title, content, username, created_at) values('8 번째 글', '물대포', '꼬부기', now());
insert into board_tb(title, content, username, created_at) values('9 번째 글', '수면가루', '버터플', now());
insert into board_tb(title, content, username, created_at) values('10 번째 글', '망각술', '야도란', now());
insert into board_tb(title, content, username, created_at) values('11 번째 글', '폭풍', '피죤투', now());